### PR TITLE
chore: Upgrade dependency on github.com/jenkins-x/jx-api/v4

### PR DESCRIPTION
**Pull request by msvticket**
Also ran go mod tidy
Fixes that jx secret removes issueProvider from jx-requirements.yaml

### CODE REVIEW

**Comment by ankitm123** [comment]
Just ran `go mod tidy` on main branch, and did not remove anything ... which version of go are you on @msvticket?

**Comment by msvticket** [comment]
I have 1.17.2.

**Comment by ankitm123** [comment]
can you downgrade to 1.15 (or use gvm to switch the version)? I have a few PRs open to upgrade to 1.17 soon though ...

**Pull request merged**
